05-17 16:59:56 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" not found; SQL statement:
SELECT numero FROM version [42102-166]
05-17 17:07:17 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Sequence "INFORMACION_PERSONAL" not found; SQL statement:
select nextval('informacion_personal') [90036-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getSequence(Schema.java:474)
	at org.h2.expression.Function.getSequence(Function.java:1278)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1126)
	at org.h2.expression.Function.getValue(Function.java:444)
	at org.h2.command.dml.Select.queryFlat(Select.java:519)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:82)
	at org.h2.command.Command.executeQuery(Command.java:187)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:177)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:07:17 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Sequence "PARAMETRO_SEQ" not found; SQL statement:
select nextval('parametro_seq') [90036-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getSequence(Schema.java:474)
	at org.h2.expression.Function.getSequence(Function.java:1278)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1126)
	at org.h2.expression.Function.getValue(Function.java:444)
	at org.h2.command.dml.Select.queryFlat(Select.java:519)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:82)
	at org.h2.command.Command.executeQuery(Command.java:187)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:177)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:07:17 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Sequence "REGION_GEN" not found; SQL statement:
select nextval('region_gen') [90036-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getSequence(Schema.java:474)
	at org.h2.expression.Function.getSequence(Function.java:1278)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1126)
	at org.h2.expression.Function.getValue(Function.java:444)
	at org.h2.command.dml.Select.queryFlat(Select.java:519)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:82)
	at org.h2.command.Command.executeQuery(Command.java:187)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:177)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:21:06 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID  SERIAL NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:21:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM INFORMATION_SCHEMA.USERS INFORMATION_SCHEMA.[*]TABLES"; SQL statement:
SELECT * FROM INFORMATION_SCHEMA.USERS INFORMATION_SCHEMA.TABLES [42000-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:23:12 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 17:23:13 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 17:25:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('material_gen', 1)
INSERT[*] INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('orden_provision_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('rol_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('cliente_gen', 1)
INSERT INTO GENERADOR_ACCION(KEY_ACCION, ID_ACCION) VALUES ('pk_accion', 0)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('deposito_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('detalle_producto_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('usuario_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('marca_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('productoDeposito_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('localidad_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('presupuesto_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('medico_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('ortopedista_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) VALUES ('observacion_gen', 1) "; SQL statement:
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('material_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('orden_provision_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('rol_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('cliente_gen', 1)
INSERT INTO generador_accion(key_accion, id_accion) values ('pk_accion', 0)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('deposito_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('detalle_producto_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('usuario_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('marca_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('productoDeposito_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('localidad_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('presupuesto_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('medico_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('ortopedista_gen', 1)
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('observacion_gen', 1) [42000-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:26:39 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:26:40 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:26:40 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:26:40 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 17:26:40 jdbc[10]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 17:35:37 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 17:35:37 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 17:35:37 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:35:37 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 17:35:38 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 17:38:52 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:38:53 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:38:54 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:38:54 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 17:38:54 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 17:52:41 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 17:52:42 jdbc[16]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:07:23 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:07:23 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:07:24 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:07:25 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:07:25 jdbc[18]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:09:07 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:09:08 jdbc[20]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:11:06 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:11:06 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:11:06 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:11:06 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:11:06 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:11:07 jdbc[22]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:12:53 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:12:53 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:12:54 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:12:55 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:12:55 jdbc[24]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:21:17 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into usuario(password,username)values(1,'root','root') [21002-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.command.dml.Insert.prepare(Insert.java:226)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:266)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:221)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:21:44 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:21:45 jdbc[26]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
05-17 18:26:26 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
05-17 18:26:26 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
05-17 18:26:26 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:662)
05-17 18:26:27 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
05-17 18:26:28 jdbc[28]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:00:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
07-12 22:00:09 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
07-12 22:01:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
07-12 22:01:19 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:01:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:01:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
07-12 22:01:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:06:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
07-12 22:06:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
07-12 22:18:29 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "VERSION" already exists; SQL statement:
CREATE TABLE VERSION (NUMERO INTEGER NOT NULL, PRIMARY KEY (NUMERO)) [42101-166]
07-12 22:18:29 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ACCION" already exists; SQL statement:
CREATE TABLE ACCION (ID BIGINT NOT NULL, CLAVE VARCHAR(255), NOMBRE VARCHAR(255), VERSION INTEGER, PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL" already exists; SQL statement:
CREATE TABLE ROL (ID BIGINT NOT NULL, DESCRIPCION VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "USUARIO" already exists; SQL statement:
CREATE TABLE USUARIO (ID BIGINT NOT NULL, BORRADO BOOLEAN, PASSWORD VARCHAR(15), USERNAME VARCHAR(20), VERSION INTEGER, id_rol BIGINT, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "INFORMACION_PERSONAL" already exists; SQL statement:
CREATE TABLE informacion_personal (ID BIGINT NOT NULL, ALTURA VARCHAR(20), APELLIDOS VARCHAR(40), DIRECCION VARCHAR(255), e_mail VARCHAR(60), EDAD VARCHAR(20), NOMBRES VARCHAR(40), PARENTEZCO VARCHAR(255), PATOLOGIA VARCHAR(255), PESO VARCHAR(20), TELEFONOFIJO VARCHAR(40), TELEFONOLABORAL VARCHAR(50), TELEFONOMOVIL VARCHAR(50), id_localidad BIGINT, id_region BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "VENDEDOR" already exists; SQL statement:
CREATE TABLE vendedor (ID BIGINT NOT NULL, nro_vendedor INTEGER, id_informacion_personal BIGINT, PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "PARAMETRO" already exists; SQL statement:
CREATE TABLE parametro (ID BIGINT NOT NULL, BORRADO BOOLEAN, PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "REGION" already exists; SQL statement:
CREATE TABLE region (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "LOCALIDAD" already exists; SQL statement:
CREATE TABLE localidad (ID BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ROL_ACCION" already exists; SQL statement:
CREATE TABLE ROL_ACCION (Rol_ID BIGINT NOT NULL, acciones_ID BIGINT NOT NULL, PRIMARY KEY (Rol_ID, acciones_ID)) [42101-166]
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_USUARIO_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_INFORMACION_PERSONAL_ID_REGION" already exists; SQL statement:
ALTER TABLE informacion_personal ADD CONSTRAINT FK_informacion_personal_id_region FOREIGN KEY (id_region) REFERENCES region (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_VENDEDOR_ID_INFORMACION_PERSONAL" already exists; SQL statement:
ALTER TABLE vendedor ADD CONSTRAINT FK_vendedor_id_informacion_personal FOREIGN KEY (id_informacion_personal) REFERENCES informacion_personal (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_ROL_ACCION_ACCIONES_ID" already exists; SQL statement:
ALTER TABLE ROL_ACCION ADD CONSTRAINT FK_ROL_ACCION_acciones_ID FOREIGN KEY (acciones_ID) REFERENCES ACCION (ID) [90045-166]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:89)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:226)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:181)
	at org.h2.server.pg.PgServerThread.process(PgServerThread.java:329)
	at org.h2.server.pg.PgServerThread.run(PgServerThread.java:81)
	at java.lang.Thread.run(Thread.java:722)
07-12 22:18:30 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "SEQUENCE" already exists; SQL statement:
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME)) [42101-166]
07-12 22:18:31 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "GENERADOR_ACCION" already exists; SQL statement:
CREATE TABLE generador_accion (key_accion VARCHAR(50) NOT NULL, id_accion DECIMAL(38), PRIMARY KEY (key_accion)) [42101-166]
